package net.vicp.sealedbook.dao.auto.model;

import java.util.Date;
import net.vicp.sealedbook.common.utils.BaseEntity;

public class CycleInfoMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 周期起始时间
     */
    private Date cycleBegin;

    /**
     * 周期结束时间
     */
    private Date cycleEnd;

    /**
     * 提交人ID
     */
    private Integer submitUserId;

    /**
     * 
     */
    private String submitIpaddress;

    /**
     * 
     */
    private Date submitDateTime;

    /**
     * 通知id
     */
    private Integer noticeId;

    /**
     * @return the value of cycle_info.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for cycle_info.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of cycle_info.cycle_begin
     * 周期起始时间
     */
    public Date getCycleBegin() {
        return cycleBegin;
    }

    /**
     * @param cycleBegin the value for cycle_info.cycle_begin
     * 周期起始时间
     */
    public void setCycleBegin(Date cycleBegin) {
        this.cycleBegin = cycleBegin;
    }

    /**
     * @return the value of cycle_info.cycle_end
     * 周期结束时间
     */
    public Date getCycleEnd() {
        return cycleEnd;
    }

    /**
     * @param cycleEnd the value for cycle_info.cycle_end
     * 周期结束时间
     */
    public void setCycleEnd(Date cycleEnd) {
        this.cycleEnd = cycleEnd;
    }

    /**
     * @return the value of cycle_info.submit_user_id
     * 提交人ID
     */
    public Integer getSubmitUserId() {
        return submitUserId;
    }

    /**
     * @param submitUserId the value for cycle_info.submit_user_id
     * 提交人ID
     */
    public void setSubmitUserId(Integer submitUserId) {
        this.submitUserId = submitUserId;
    }

    /**
     * @return the value of cycle_info.submit_ipaddress
     * 
     */
    public String getSubmitIpaddress() {
        return submitIpaddress;
    }

    /**
     * @param submitIpaddress the value for cycle_info.submit_ipaddress
     * 
     */
    public void setSubmitIpaddress(String submitIpaddress) {
        this.submitIpaddress = submitIpaddress == null ? null : submitIpaddress.trim();
    }

    /**
     * @return the value of cycle_info.submit_date_time
     * 
     */
    public Date getSubmitDateTime() {
        return submitDateTime;
    }

    /**
     * @param submitDateTime the value for cycle_info.submit_date_time
     * 
     */
    public void setSubmitDateTime(Date submitDateTime) {
        this.submitDateTime = submitDateTime;
    }

    /**
     * @return the value of cycle_info.notice_id
     * 通知id
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * @param noticeId the value for cycle_info.notice_id
     * 通知id
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CycleInfoMo other = (CycleInfoMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCycleBegin() == null ? other.getCycleBegin() == null : this.getCycleBegin().equals(other.getCycleBegin()))
            && (this.getCycleEnd() == null ? other.getCycleEnd() == null : this.getCycleEnd().equals(other.getCycleEnd()))
            && (this.getSubmitUserId() == null ? other.getSubmitUserId() == null : this.getSubmitUserId().equals(other.getSubmitUserId()))
            && (this.getSubmitIpaddress() == null ? other.getSubmitIpaddress() == null : this.getSubmitIpaddress().equals(other.getSubmitIpaddress()))
            && (this.getSubmitDateTime() == null ? other.getSubmitDateTime() == null : this.getSubmitDateTime().equals(other.getSubmitDateTime()))
            && (this.getNoticeId() == null ? other.getNoticeId() == null : this.getNoticeId().equals(other.getNoticeId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCycleBegin() == null) ? 0 : getCycleBegin().hashCode());
        result = prime * result + ((getCycleEnd() == null) ? 0 : getCycleEnd().hashCode());
        result = prime * result + ((getSubmitUserId() == null) ? 0 : getSubmitUserId().hashCode());
        result = prime * result + ((getSubmitIpaddress() == null) ? 0 : getSubmitIpaddress().hashCode());
        result = prime * result + ((getSubmitDateTime() == null) ? 0 : getSubmitDateTime().hashCode());
        result = prime * result + ((getNoticeId() == null) ? 0 : getNoticeId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cycleBegin=").append(cycleBegin);
        sb.append(", cycleEnd=").append(cycleEnd);
        sb.append(", submitUserId=").append(submitUserId);
        sb.append(", submitIpaddress=").append(submitIpaddress);
        sb.append(", submitDateTime=").append(submitDateTime);
        sb.append(", noticeId=").append(noticeId);
        sb.append("]");
        return sb.toString();
    }
}