package net.vicp.sealedbook.dao.auto.model;

import java.util.Date;
import net.vicp.sealedbook.common.utils.BaseEntity;

public class NoticeReceiveMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 通知ID,notice_info表id
     */
    private Integer noticeId;

    /**
     * 接收用户ID
     */
    private Integer receiveUserId;

    /**
     * 
     */
    private Date receiveDateTime;

    /**
     * 
     */
    private String receiveDeviceNumber;

    /**
     * 
     */
    private String receiveIpAddress;

    /**
     * @return the value of notice_receive.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for notice_receive.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of notice_receive.notice_id
     * 通知ID,notice_info表id
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * @param noticeId the value for notice_receive.notice_id
     * 通知ID,notice_info表id
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * @return the value of notice_receive.receive_user_id
     * 接收用户ID
     */
    public Integer getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * @param receiveUserId the value for notice_receive.receive_user_id
     * 接收用户ID
     */
    public void setReceiveUserId(Integer receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * @return the value of notice_receive.receive_date_time
     * 
     */
    public Date getReceiveDateTime() {
        return receiveDateTime;
    }

    /**
     * @param receiveDateTime the value for notice_receive.receive_date_time
     * 
     */
    public void setReceiveDateTime(Date receiveDateTime) {
        this.receiveDateTime = receiveDateTime;
    }

    /**
     * @return the value of notice_receive.receive_device_number
     * 
     */
    public String getReceiveDeviceNumber() {
        return receiveDeviceNumber;
    }

    /**
     * @param receiveDeviceNumber the value for notice_receive.receive_device_number
     * 
     */
    public void setReceiveDeviceNumber(String receiveDeviceNumber) {
        this.receiveDeviceNumber = receiveDeviceNumber == null ? null : receiveDeviceNumber.trim();
    }

    /**
     * @return the value of notice_receive.receive_ip_address
     * 
     */
    public String getReceiveIpAddress() {
        return receiveIpAddress;
    }

    /**
     * @param receiveIpAddress the value for notice_receive.receive_ip_address
     * 
     */
    public void setReceiveIpAddress(String receiveIpAddress) {
        this.receiveIpAddress = receiveIpAddress == null ? null : receiveIpAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NoticeReceiveMo other = (NoticeReceiveMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNoticeId() == null ? other.getNoticeId() == null : this.getNoticeId().equals(other.getNoticeId()))
            && (this.getReceiveUserId() == null ? other.getReceiveUserId() == null : this.getReceiveUserId().equals(other.getReceiveUserId()))
            && (this.getReceiveDateTime() == null ? other.getReceiveDateTime() == null : this.getReceiveDateTime().equals(other.getReceiveDateTime()))
            && (this.getReceiveDeviceNumber() == null ? other.getReceiveDeviceNumber() == null : this.getReceiveDeviceNumber().equals(other.getReceiveDeviceNumber()))
            && (this.getReceiveIpAddress() == null ? other.getReceiveIpAddress() == null : this.getReceiveIpAddress().equals(other.getReceiveIpAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNoticeId() == null) ? 0 : getNoticeId().hashCode());
        result = prime * result + ((getReceiveUserId() == null) ? 0 : getReceiveUserId().hashCode());
        result = prime * result + ((getReceiveDateTime() == null) ? 0 : getReceiveDateTime().hashCode());
        result = prime * result + ((getReceiveDeviceNumber() == null) ? 0 : getReceiveDeviceNumber().hashCode());
        result = prime * result + ((getReceiveIpAddress() == null) ? 0 : getReceiveIpAddress().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", noticeId=").append(noticeId);
        sb.append(", receiveUserId=").append(receiveUserId);
        sb.append(", receiveDateTime=").append(receiveDateTime);
        sb.append(", receiveDeviceNumber=").append(receiveDeviceNumber);
        sb.append(", receiveIpAddress=").append(receiveIpAddress);
        sb.append("]");
        return sb.toString();
    }
}