package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.enums.YesNoEnum;
import net.vicp.sealedbook.common.utils.BaseEntity;
import net.vicp.sealedbook.enums.SystemResourceTypeEnum;

public class SystemResourceMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private String resourceName;

    /**
     * 
     */
    private String resourceUrl;

    /**
     * 
     */
    private String resourceParam;

    /**
     * 
     */
    private YesNoEnum isDeleted;

    /**
     * 
     */
    private Integer ordered;

    /**
     * 
     */
    private String functionId;

    /**
     * 
     */
    private SystemResourceTypeEnum resourceType;

    /**
     * @return the value of sys_security_resource.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for sys_security_resource.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of sys_security_resource.resource_name
     * 
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * @param resourceName the value for sys_security_resource.resource_name
     * 
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * @return the value of sys_security_resource.resource_url
     * 
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * @param resourceUrl the value for sys_security_resource.resource_url
     * 
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * @return the value of sys_security_resource.resource_param
     * 
     */
    public String getResourceParam() {
        return resourceParam;
    }

    /**
     * @param resourceParam the value for sys_security_resource.resource_param
     * 
     */
    public void setResourceParam(String resourceParam) {
        this.resourceParam = resourceParam == null ? null : resourceParam.trim();
    }

    /**
     * @return the value of sys_security_resource.is_deleted
     * 
     */
    public YesNoEnum getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the value for sys_security_resource.is_deleted
     * 
     */
    public void setIsDeleted(YesNoEnum isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * @return the value of sys_security_resource.ordered
     * 
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * @param ordered the value for sys_security_resource.ordered
     * 
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }

    /**
     * @return the value of sys_security_resource.function_id
     * 
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * @param functionId the value for sys_security_resource.function_id
     * 
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }

    /**
     * @return the value of sys_security_resource.resource_type
     * 
     */
    public SystemResourceTypeEnum getResourceType() {
        return resourceType;
    }

    /**
     * @param resourceType the value for sys_security_resource.resource_type
     * 
     */
    public void setResourceType(SystemResourceTypeEnum resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemResourceMo other = (SystemResourceMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getResourceName() == null ? other.getResourceName() == null : this.getResourceName().equals(other.getResourceName()))
            && (this.getResourceUrl() == null ? other.getResourceUrl() == null : this.getResourceUrl().equals(other.getResourceUrl()))
            && (this.getResourceParam() == null ? other.getResourceParam() == null : this.getResourceParam().equals(other.getResourceParam()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getOrdered() == null ? other.getOrdered() == null : this.getOrdered().equals(other.getOrdered()))
            && (this.getFunctionId() == null ? other.getFunctionId() == null : this.getFunctionId().equals(other.getFunctionId()))
            && (this.getResourceType() == null ? other.getResourceType() == null : this.getResourceType().equals(other.getResourceType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getResourceName() == null) ? 0 : getResourceName().hashCode());
        result = prime * result + ((getResourceUrl() == null) ? 0 : getResourceUrl().hashCode());
        result = prime * result + ((getResourceParam() == null) ? 0 : getResourceParam().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getOrdered() == null) ? 0 : getOrdered().hashCode());
        result = prime * result + ((getFunctionId() == null) ? 0 : getFunctionId().hashCode());
        result = prime * result + ((getResourceType() == null) ? 0 : getResourceType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", resourceName=").append(resourceName);
        sb.append(", resourceUrl=").append(resourceUrl);
        sb.append(", resourceParam=").append(resourceParam);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", ordered=").append(ordered);
        sb.append(", functionId=").append(functionId);
        sb.append(", resourceType=").append(resourceType);
        sb.append("]");
        return sb.toString();
    }
}