package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.enums.YesNoEnum;
import net.vicp.sealedbook.common.utils.BaseEntity;

public class SystemFunctionMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private String name;

    /**
     * 
     */
    private Integer ordered;

    /**
     * 
     */
    private YesNoEnum isDeleted;

    /**
     * @return the value of sys_security_function.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for sys_security_function.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of sys_security_function.name
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the value for sys_security_function.name
     * 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return the value of sys_security_function.ordered
     * 
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * @param ordered the value for sys_security_function.ordered
     * 
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }

    /**
     * @return the value of sys_security_function.is_deleted
     * 
     */
    public YesNoEnum getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the value for sys_security_function.is_deleted
     * 
     */
    public void setIsDeleted(YesNoEnum isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemFunctionMo other = (SystemFunctionMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOrdered() == null ? other.getOrdered() == null : this.getOrdered().equals(other.getOrdered()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOrdered() == null) ? 0 : getOrdered().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", ordered=").append(ordered);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}