package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.enums.YesNoEnum;
import net.vicp.sealedbook.common.utils.BaseEntity;

public class SystemModuleMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private String moduleName;

    /**
     * 
     */
    private String icon;

    /**
     * 
     */
    private Integer ordered;

    /**
     * 
     */
    private String entryUrl;

    /**
     * 
     */
    private Integer parentId;

    /**
     * 
     */
    private YesNoEnum isDeleted;

    /**
     * @return the value of sys_security_module.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for sys_security_module.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of sys_security_module.module_name
     * 
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * @param moduleName the value for sys_security_module.module_name
     * 
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * @return the value of sys_security_module.icon
     * 
     */
    public String getIcon() {
        return icon;
    }

    /**
     * @param icon the value for sys_security_module.icon
     * 
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * @return the value of sys_security_module.ordered
     * 
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * @param ordered the value for sys_security_module.ordered
     * 
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }

    /**
     * @return the value of sys_security_module.entry_url
     * 
     */
    public String getEntryUrl() {
        return entryUrl;
    }

    /**
     * @param entryUrl the value for sys_security_module.entry_url
     * 
     */
    public void setEntryUrl(String entryUrl) {
        this.entryUrl = entryUrl == null ? null : entryUrl.trim();
    }

    /**
     * @return the value of sys_security_module.parent_id
     * 
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * @param parentId the value for sys_security_module.parent_id
     * 
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * @return the value of sys_security_module.is_deleted
     * 
     */
    public YesNoEnum getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the value for sys_security_module.is_deleted
     * 
     */
    public void setIsDeleted(YesNoEnum isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemModuleMo other = (SystemModuleMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getModuleName() == null ? other.getModuleName() == null : this.getModuleName().equals(other.getModuleName()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getOrdered() == null ? other.getOrdered() == null : this.getOrdered().equals(other.getOrdered()))
            && (this.getEntryUrl() == null ? other.getEntryUrl() == null : this.getEntryUrl().equals(other.getEntryUrl()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getModuleName() == null) ? 0 : getModuleName().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getOrdered() == null) ? 0 : getOrdered().hashCode());
        result = prime * result + ((getEntryUrl() == null) ? 0 : getEntryUrl().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", icon=").append(icon);
        sb.append(", ordered=").append(ordered);
        sb.append(", entryUrl=").append(entryUrl);
        sb.append(", parentId=").append(parentId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}