package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.utils.BaseEntity;

public class SystemRoleUserMapperMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private Integer userId;

    /**
     * 
     */
    private Integer roleId;

    /**
     * 
     */
    private Integer orderFlag;

    /**
     * @return the value of sys_security_ur_map.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for sys_security_ur_map.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of sys_security_ur_map.user_id
     * 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * @param userId the value for sys_security_ur_map.user_id
     * 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * @return the value of sys_security_ur_map.role_id
     * 
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * @param roleId the value for sys_security_ur_map.role_id
     * 
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * @return the value of sys_security_ur_map.order_flag
     * 
     */
    public Integer getOrderFlag() {
        return orderFlag;
    }

    /**
     * @param orderFlag the value for sys_security_ur_map.order_flag
     * 
     */
    public void setOrderFlag(Integer orderFlag) {
        this.orderFlag = orderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemRoleUserMapperMo other = (SystemRoleUserMapperMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getOrderFlag() == null ? other.getOrderFlag() == null : this.getOrderFlag().equals(other.getOrderFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getOrderFlag() == null) ? 0 : getOrderFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", orderFlag=").append(orderFlag);
        sb.append("]");
        return sb.toString();
    }
}