package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.enums.GenderEnum;
import net.vicp.sealedbook.common.utils.BaseEntity;

public class SystemUserMo extends BaseEntity {
    /**
     * 
     */
    private Integer id;

    /**
     * 登录账号
     */
    private String account;

    /**
     * 系统中显示名称
     */
    private String showName;

    /**
     * 登录密码
     */
    private String password;

    /**
     * 身份证号
     */
    private String idCard;

    /**
     * 性别
     */
    private GenderEnum sex;

    /**
     * @return the value of sys_security_user.id
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for sys_security_user.id
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of sys_security_user.account
     * 登录账号
     */
    public String getAccount() {
        return account;
    }

    /**
     * @param account the value for sys_security_user.account
     * 登录账号
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * @return the value of sys_security_user.show_name
     * 系统中显示名称
     */
    public String getShowName() {
        return showName;
    }

    /**
     * @param showName the value for sys_security_user.show_name
     * 系统中显示名称
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * @return the value of sys_security_user.password
     * 登录密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the value for sys_security_user.password
     * 登录密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * @return the value of sys_security_user.id_card
     * 身份证号
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * @param idCard the value for sys_security_user.id_card
     * 身份证号
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * @return the value of sys_security_user.sex
     * 性别
     */
    public GenderEnum getSex() {
        return sex;
    }

    /**
     * @param sex the value for sys_security_user.sex
     * 性别
     */
    public void setSex(GenderEnum sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemUserMo other = (SystemUserMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getShowName() == null ? other.getShowName() == null : this.getShowName().equals(other.getShowName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getIdCard() == null ? other.getIdCard() == null : this.getIdCard().equals(other.getIdCard()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getShowName() == null) ? 0 : getShowName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getIdCard() == null) ? 0 : getIdCard().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", showName=").append(showName);
        sb.append(", password=").append(password);
        sb.append(", idCard=").append(idCard);
        sb.append(", sex=").append(sex);
        sb.append("]");
        return sb.toString();
    }
}