package net.vicp.sealedbook.dao.auto.model;

import net.vicp.sealedbook.common.utils.BaseEntity;

public class SystemModuleFunctionMapperMo extends BaseEntity {
    /**
     * 
     */
    private String id;

    /**
     * 
     */
    private Integer moduleId;

    /**
     * 
     */
    private Integer functionId;

    /**
     * @return the value of sys_security_mf_map.id
     * 
     */
    public String getId() {
        return id;
    }

    /**
     * @param id the value for sys_security_mf_map.id
     * 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * @return the value of sys_security_mf_map.module_id
     * 
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * @param moduleId the value for sys_security_mf_map.module_id
     * 
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * @return the value of sys_security_mf_map.function_id
     * 
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * @param functionId the value for sys_security_mf_map.function_id
     * 
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_mf_map
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemModuleFunctionMapperMo other = (SystemModuleFunctionMapperMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getModuleId() == null ? other.getModuleId() == null : this.getModuleId().equals(other.getModuleId()))
            && (this.getFunctionId() == null ? other.getFunctionId() == null : this.getFunctionId().equals(other.getFunctionId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_mf_map
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getModuleId() == null) ? 0 : getModuleId().hashCode());
        result = prime * result + ((getFunctionId() == null) ? 0 : getFunctionId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_mf_map
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", moduleId=").append(moduleId);
        sb.append(", functionId=").append(functionId);
        sb.append("]");
        return sb.toString();
    }
}