package net.vicp.sealedbook.dao.auto.criteria;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CycleInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public CycleInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCycleBeginIsNull() {
            addCriterion("cycle_begin is null");
            return (Criteria) this;
        }

        public Criteria andCycleBeginIsNotNull() {
            addCriterion("cycle_begin is not null");
            return (Criteria) this;
        }

        public Criteria andCycleBeginEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_begin =", value, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginNotEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_begin <>", value, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginGreaterThan(Date value) {
            addCriterionForJDBCDate("cycle_begin >", value, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_begin >=", value, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginLessThan(Date value) {
            addCriterionForJDBCDate("cycle_begin <", value, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_begin <=", value, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginIn(List<Date> values) {
            addCriterionForJDBCDate("cycle_begin in", values, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginNotIn(List<Date> values) {
            addCriterionForJDBCDate("cycle_begin not in", values, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cycle_begin between", value1, value2, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleBeginNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cycle_begin not between", value1, value2, "cycleBegin");
            return (Criteria) this;
        }

        public Criteria andCycleEndIsNull() {
            addCriterion("cycle_end is null");
            return (Criteria) this;
        }

        public Criteria andCycleEndIsNotNull() {
            addCriterion("cycle_end is not null");
            return (Criteria) this;
        }

        public Criteria andCycleEndEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_end =", value, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndNotEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_end <>", value, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndGreaterThan(Date value) {
            addCriterionForJDBCDate("cycle_end >", value, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_end >=", value, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndLessThan(Date value) {
            addCriterionForJDBCDate("cycle_end <", value, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cycle_end <=", value, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndIn(List<Date> values) {
            addCriterionForJDBCDate("cycle_end in", values, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndNotIn(List<Date> values) {
            addCriterionForJDBCDate("cycle_end not in", values, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cycle_end between", value1, value2, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andCycleEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cycle_end not between", value1, value2, "cycleEnd");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdIsNull() {
            addCriterion("submit_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdIsNotNull() {
            addCriterion("submit_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdEqualTo(Integer value) {
            addCriterion("submit_user_id =", value, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdNotEqualTo(Integer value) {
            addCriterion("submit_user_id <>", value, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdGreaterThan(Integer value) {
            addCriterion("submit_user_id >", value, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("submit_user_id >=", value, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdLessThan(Integer value) {
            addCriterion("submit_user_id <", value, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("submit_user_id <=", value, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdIn(List<Integer> values) {
            addCriterion("submit_user_id in", values, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdNotIn(List<Integer> values) {
            addCriterion("submit_user_id not in", values, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdBetween(Integer value1, Integer value2) {
            addCriterion("submit_user_id between", value1, value2, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("submit_user_id not between", value1, value2, "submitUserId");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressIsNull() {
            addCriterion("submit_ipaddress is null");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressIsNotNull() {
            addCriterion("submit_ipaddress is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressEqualTo(String value) {
            addCriterion("submit_ipaddress =", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressNotEqualTo(String value) {
            addCriterion("submit_ipaddress <>", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressGreaterThan(String value) {
            addCriterion("submit_ipaddress >", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("submit_ipaddress >=", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressLessThan(String value) {
            addCriterion("submit_ipaddress <", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressLessThanOrEqualTo(String value) {
            addCriterion("submit_ipaddress <=", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressLike(String value) {
            addCriterion("submit_ipaddress like", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressNotLike(String value) {
            addCriterion("submit_ipaddress not like", value, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressIn(List<String> values) {
            addCriterion("submit_ipaddress in", values, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressNotIn(List<String> values) {
            addCriterion("submit_ipaddress not in", values, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressBetween(String value1, String value2) {
            addCriterion("submit_ipaddress between", value1, value2, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitIpaddressNotBetween(String value1, String value2) {
            addCriterion("submit_ipaddress not between", value1, value2, "submitIpaddress");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeIsNull() {
            addCriterion("submit_date_time is null");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeIsNotNull() {
            addCriterion("submit_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeEqualTo(Date value) {
            addCriterion("submit_date_time =", value, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeNotEqualTo(Date value) {
            addCriterion("submit_date_time <>", value, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeGreaterThan(Date value) {
            addCriterion("submit_date_time >", value, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("submit_date_time >=", value, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeLessThan(Date value) {
            addCriterion("submit_date_time <", value, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("submit_date_time <=", value, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeIn(List<Date> values) {
            addCriterion("submit_date_time in", values, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeNotIn(List<Date> values) {
            addCriterion("submit_date_time not in", values, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeBetween(Date value1, Date value2) {
            addCriterion("submit_date_time between", value1, value2, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andSubmitDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("submit_date_time not between", value1, value2, "submitDateTime");
            return (Criteria) this;
        }

        public Criteria andNoticeIdIsNull() {
            addCriterion("notice_id is null");
            return (Criteria) this;
        }

        public Criteria andNoticeIdIsNotNull() {
            addCriterion("notice_id is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeIdEqualTo(Integer value) {
            addCriterion("notice_id =", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotEqualTo(Integer value) {
            addCriterion("notice_id <>", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdGreaterThan(Integer value) {
            addCriterion("notice_id >", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("notice_id >=", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdLessThan(Integer value) {
            addCriterion("notice_id <", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdLessThanOrEqualTo(Integer value) {
            addCriterion("notice_id <=", value, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdIn(List<Integer> values) {
            addCriterion("notice_id in", values, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotIn(List<Integer> values) {
            addCriterion("notice_id not in", values, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdBetween(Integer value1, Integer value2) {
            addCriterion("notice_id between", value1, value2, "noticeId");
            return (Criteria) this;
        }

        public Criteria andNoticeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("notice_id not between", value1, value2, "noticeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cycle_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}