package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.CycleInfoExample;
import net.vicp.sealedbook.dao.auto.model.CycleInfoMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CycleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int countByExample(CycleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int deleteByExample(CycleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int insert(CycleInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int insertBatch(List<CycleInfoMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int insertSelective(CycleInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    List<CycleInfoMo> selectByExample(CycleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    CycleInfoMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CycleInfoMo record, @Param("example") CycleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CycleInfoMo record, @Param("example") CycleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CycleInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CycleInfoMo record);
}