package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.NoticeInfoExample;
import net.vicp.sealedbook.dao.auto.model.NoticeInfoMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface NoticeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int countByExample(NoticeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int deleteByExample(NoticeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int insert(NoticeInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int insertBatch(List<NoticeInfoMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int insertSelective(NoticeInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    List<NoticeInfoMo> selectByExample(NoticeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    NoticeInfoMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoticeInfoMo record, @Param("example") NoticeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoticeInfoMo record, @Param("example") NoticeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeInfoMo record);
}