package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.NoticeReceiveExample;
import net.vicp.sealedbook.dao.auto.model.NoticeReceiveMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface NoticeReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int countByExample(NoticeReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int deleteByExample(NoticeReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int insert(NoticeReceiveMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int insertBatch(List<NoticeReceiveMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int insertSelective(NoticeReceiveMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    List<NoticeReceiveMo> selectByExample(NoticeReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    NoticeReceiveMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoticeReceiveMo record, @Param("example") NoticeReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoticeReceiveMo record, @Param("example") NoticeReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeReceiveMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_receive
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeReceiveMo record);
}