package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemModuleExample;
import net.vicp.sealedbook.dao.auto.model.SystemModuleMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int countByExample(SystemModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int deleteByExample(SystemModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int insert(SystemModuleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemModuleMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int insertSelective(SystemModuleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    List<SystemModuleMo> selectByExample(SystemModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    SystemModuleMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemModuleMo record, @Param("example") SystemModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemModuleMo record, @Param("example") SystemModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemModuleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemModuleMo record);
}