package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemFunctionExample;
import net.vicp.sealedbook.dao.auto.model.SystemFunctionMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int countByExample(SystemFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int deleteByExample(SystemFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int insert(SystemFunctionMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemFunctionMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int insertSelective(SystemFunctionMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    List<SystemFunctionMo> selectByExample(SystemFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    SystemFunctionMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemFunctionMo record, @Param("example") SystemFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemFunctionMo record, @Param("example") SystemFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemFunctionMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_function
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemFunctionMo record);
}