package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemRoleUserMapperExample;
import net.vicp.sealedbook.dao.auto.model.SystemRoleUserMapperMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemRoleUserMapperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int countByExample(SystemRoleUserMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int deleteByExample(SystemRoleUserMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int insert(SystemRoleUserMapperMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemRoleUserMapperMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoleUserMapperMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    List<SystemRoleUserMapperMo> selectByExample(SystemRoleUserMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    SystemRoleUserMapperMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemRoleUserMapperMo record, @Param("example") SystemRoleUserMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemRoleUserMapperMo record, @Param("example") SystemRoleUserMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRoleUserMapperMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_ur_map
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRoleUserMapperMo record);
}