package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemResourceExample;
import net.vicp.sealedbook.dao.auto.model.SystemResourceMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int countByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int deleteByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int insert(SystemResourceMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemResourceMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int insertSelective(SystemResourceMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    List<SystemResourceMo> selectByExample(SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    SystemResourceMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemResourceMo record, @Param("example") SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemResourceMo record, @Param("example") SystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemResourceMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemResourceMo record);
}