package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemRoleFunctionMapperExample;
import net.vicp.sealedbook.dao.auto.model.SystemRoleFunctionMapperMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemRoleFunctionMapperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int countByExample(SystemRoleFunctionMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int deleteByExample(SystemRoleFunctionMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int insert(SystemRoleFunctionMapperMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemRoleFunctionMapperMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoleFunctionMapperMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    List<SystemRoleFunctionMapperMo> selectByExample(SystemRoleFunctionMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    SystemRoleFunctionMapperMo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemRoleFunctionMapperMo record, @Param("example") SystemRoleFunctionMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemRoleFunctionMapperMo record, @Param("example") SystemRoleFunctionMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRoleFunctionMapperMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_rf_map
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRoleFunctionMapperMo record);
}