package net.vicp.sealedbook.dao.auto.mapper;

import java.util.List;
import net.vicp.sealedbook.dao.auto.criteria.SystemRoleExample;
import net.vicp.sealedbook.dao.auto.model.SystemRoleMo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int countByExample(SystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int deleteByExample(SystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int insert(SystemRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int insertBatch(List<SystemRoleMo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    List<SystemRoleMo> selectByExample(SystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    SystemRoleMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemRoleMo record, @Param("example") SystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemRoleMo record, @Param("example") SystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRoleMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_security_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRoleMo record);
}